spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:h2:mem:bdAuth
        username: root
        password: root
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
---

server:
    port: 8084
  
---
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        prefer-ip-address: true
        
---

config:
    security:
        oauth:
            client:
                id: web_client
                secret: 987654321
            jwt:
                key: 987654321

       

