spring:
    application:
        name: answer-service 
    datasource:
        url: jdbc:h2:mem:answer
        username: root
        password: root
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
---

server:
    port: 8082

       

