spring:
    application:
        name: user-service
    datasource:
        url: jdbc:h2:mem:bdUser
        username: root
        password: root
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    security:
        user:
            name: root
            password: root
---

server:
    port: 8084

       

