spring:
    application:
        name: question-service 
    datasource:
        url: jdbc:h2:mem:bdQuestion
        username: root
        password: root
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
---

server:
    port: 8081

---

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        prefer-ip-address: true

